/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'tab': '834px',  // iPad竖屏
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-manrope)', 'var(--font-inter)', 'ui-sans-serif', 'system-ui'],
        display: ['var(--font-syne)', 'var(--font-inter)', 'ui-sans-serif', 'system-ui'],
        'sf-pro-display': ['"SF Pro Display"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        'sf-pro-text': ['"SF Pro Text"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
      },
      colors: {
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
          50: '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        glass: {
          DEFAULT: 'var(--glass-default)',
          light: 'var(--glass-default)',
          border: 'var(--glass-border)',
          glow: 'var(--glass-glow)',
        },
        tech: {
          darkblue: 'var(--tech-darkblue)',
          deepblue: 'var(--tech-deepblue)',
          cyan: 'var(--tech-cyan)',
          lightcyan: 'var(--tech-lightcyan)',
          sky: 'var(--tech-sky)',
          // 扩展色阶
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        music: {
          primary: '#fa2d2f',
          secondary: '#ff3b30',
          hover: '#ff6961',
          active: '#d32f2f',
        },
        'macos-light': {
          background: '#F5F5F7',
          surface: '#FFFFFF',
          border: 'rgba(0,0,0,0.08)',
          'text-primary': '#1D1D1F',
          'text-secondary': 'rgba(0,0,0,0.6)',
          'text-tertiary': 'rgba(0,0,0,0.4)',
          'text-disabled': 'rgba(0,0,0,0.3)',
        },
        'macos-dark': {
          background: '#000000',
          surface: '#1C1C1E',
          border: 'rgba(255,255,255,0.08)',
          'text-primary': '#FFFFFF',
          'text-secondary': 'rgba(255,255,255,0.6)',
          'text-tertiary': 'rgba(255,255,255,0.4)',
          'text-disabled': 'rgba(255,255,255,0.3)',
        },
        success: {
          DEFAULT: 'var(--success)',
          foreground: 'var(--success-foreground)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          foreground: 'var(--warning-foreground)',
        },
        error: {
          DEFAULT: 'var(--error)',
          foreground: 'var(--error-foreground)',
        },
        info: {
          DEFAULT: 'var(--info)',
          foreground: 'var(--info-foreground)',
        },
        'text-primary': 'var(--text-primary-high-contrast)',
        'text-secondary': 'var(--text-secondary-high-contrast)',
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'macos-xs': '8px',
        'macos-sm': '12px',
        'macos-md': '16px',
        'macos-lg': '20px',
        'macos-xl': '24px',
        'macos-2xl': '32px',
        'macos-3xl': '40px',
      },
      // 统一定义keyframes（只保留一次）
      keyframes: {
        'fadeIn': {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        'slideUp': {
          from: { opacity: 0, transform: 'translateY(20px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        },
        'slideDown': {
          from: { opacity: 0, transform: 'translateY(-20px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        },
        'slideLeft': {
          from: { opacity: 0, transform: 'translateX(20px)' },
          to: { opacity: 1, transform: 'translateX(0)' },
        },
        'slideRight': {
          from: { opacity: 0, transform: 'translateX(-20px)' },
          to: { opacity: 1, transform: 'translateX(0)' },
        },
        'scaleIn': {
          from: { opacity: 0, transform: 'scale(0.95)' },
          to: { opacity: 1, transform: 'scale(1)' },
        },
        'scaleOut': {
          from: { opacity: 1, transform: 'scale(1)' },
          to: { opacity: 0, transform: 'scale(0.95)' },
        },
        'playerSlideUp': {
          from: { transform: 'translateY(100%)' },
          to: { transform: 'translateY(0)' },
        },
        'buttonBounce': {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(0.95)' },
          '100%': { transform: 'scale(1)' },
        },
        'soundWave': {
          '0%, 100%': { transform: 'scaleY(1)' },
          '50%': { transform: 'scaleY(0.5)' },
        },
        'progressPulse': {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.8 },
        },
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        'rainbow-hue': {
          '0%, 100%': { '--rainbow-hue': '0deg' },
          '100%': { '--rainbow-hue': '360deg' },
        },
        'glass-float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 15px rgba(6, 182, 212, 0.3)' },
          '50%': { boxShadow: '0 0 25px rgba(6, 182, 212, 0.6)' },
        },
        'gradient-move': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-left': {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'scale-fade-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'ripple': {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-scale-up': {
          from: { opacity: 0, transform: 'translateY(30px) scale(0.95)' },
          to: { opacity: 1, transform: 'translateY(0) scale(1)' },
        },
        'float-improved': {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px) scale(1)' },
          '25%': { transform: 'translateY(-15px) translateX(5px) scale(1.02)' },
          '50%': { transform: 'translateY(-20px) translateX(-5px) scale(1.05)' },
          '75%': { transform: 'translateY(-10px) translateX(3px) scale(1.02)' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(6, 182, 212, 0.3), 0 0 40px rgba(6, 182, 212, 0.1)' },
          '50%': { boxShadow: '0 0 30px rgba(6, 182, 212, 0.5), 0 0 60px rgba(6, 182, 212, 0.2)' },
        },
        'slide-in-right': {
          from: { opacity: 0, transform: 'translateX(30px)' },
          to: { opacity: 1, transform: 'translateX(0)' },
        },
        'slide-from-top': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'vertical-scroll': {
          '0%': { transform: 'translateY(-25%)' },
          '100%': { transform: 'translateY(25%)' },
        },
        'rotate-y-180': {
          '0%': { transform: 'rotateY(0deg)' },
          '100%': { transform: 'rotateY(180deg)' },
        },
        'scanline': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        'holo-glow': {
          '0%, 100%': { boxShadow: '0 0 10px rgba(0,217,255,0.2)' },
          '50%': { boxShadow: '0 0 20px rgba(0,217,255,0.4)' },
        },
        'particle-explode': {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '1' },
          '100%': { transform: 'translate(var(--tx, 0), var(--ty, 0)) scale(0)', opacity: '0' },
        },
        'tech-border': {
          '0%, 100%': { borderColor: 'rgba(0,217,255,0.3)' },
          '50%': { borderColor: 'rgba(0,217,255,0.6)' },
        },
        'rainbow-shift': {
          '0%': { filter: 'hue-rotate(0deg)' },
          '100%': { filter: 'hue-rotate(360deg)' },
        },
        'rainbow-hue': {
          '0%, 100%': { '--rainbow-hue': '0deg' },
          '100%': { '--rainbow-hue': '360deg' },
        },
        'level-glow': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(255,255,255,0)' },
          '50%': { boxShadow: '0 0 0 8px rgba(255,255,255,0.3)' },
        },
      },
      // 统一定义animation（只保留一次）
      animation: {
        'fade-in': 'fadeIn 300ms cubic-bezier(0.0, 0.0, 0.2, 1)',
        'slide-up': 'slideUp 300ms cubic-bezier(0.0, 0.0, 0.2, 1)',
        'slide-down': 'slideDown 300ms cubic-bezier(0.0, 0.0, 0.2, 1)',
        'slide-left': 'slideLeft 300ms cubic-bezier(0.0, 0.0, 0.2, 1)',
        'slide-right': 'slideRight 300ms cubic-bezier(0.0, 0.0, 0.2, 1)',
        'scale-in': 'scaleIn 300ms cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'scale-out': 'scaleOut 300ms cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'player-slide-up': 'playerSlideUp 400ms cubic-bezier(0.25, 0.1, 0.25, 1)',
        'button-bounce': 'buttonBounce 150ms cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'sound-wave': 'soundWave 1s ease-in-out infinite',
        'progress-pulse': 'progressPulse 2s ease-in-out infinite',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'glass-float': 'glass-float 6s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'gradient-move': 'gradient-move 8s ease infinite',
        'fade-in-up': 'fade-in-up 0.6s ease-out forwards',
        'slide-in-left': 'slide-in-left 0.6s ease-out forwards',
        'scale-fade-in': 'scale-fade-in 0.5s ease-out forwards',
        'ripple': 'ripple 0.6s ease-out forwards',
        'fade-in': 'fade-in 0.6s ease-out forwards',
        'fade-scale-up': 'fade-scale-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'float-improved': 'float-improved 8s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        'slide-in-right': 'slide-in-right 0.6s ease-out forwards',
        'slide-from-top': 'slide-from-top 1.5s ease-out forwards',
        'vertical-scroll': 'vertical-scroll 20s linear infinite',
        'spin-slow': 'spin 8s linear infinite',
        'rotate-y-180': 'rotate-y-180 0.7s ease-in-out forwards',
        'backface-hidden': 'backface-hidden 0s ease-in-out forwards',
        'scanline': 'scanline 2s linear infinite',
        'holo-glow': 'holo-glow 2s ease-in-out infinite',
        'particle-explode': 'particle-explode 0.8s ease-out forwards',
        'tech-border': 'tech-border 2s ease-in-out infinite',
        'rainbow-shift': 'rainbow-shift 3s linear infinite',
        'rainbow-hue': 'rainbow-hue 3s linear infinite',
        'level-glow': 'level-glow 2s ease-in-out infinite',
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
      },
      transitionTimingFunction: {
        'bounce': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      transitionDuration: {
        '250': '250ms',
        '350': '350ms',
        '450': '450ms',
      },
      transitionDelay: {
        '50': '50ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '250': '250ms',
        '300': '300ms',
        '400': '400ms',
        '500': '500ms',
      },
      boxShadow: {
        'macos-1': '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
        'macos-2': '0 3px 6px rgba(0,0,0,0.15), 0 2px 4px rgba(0,0,0,0.12)',
        'macos-3': '0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23)',
        'macos-4': '0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22)',
        'macos-5': '0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22)',
        'macos-glass-1': '0 8px 32px rgba(0,0,0,0.04)',
        'macos-glass-2': '0 8px 32px rgba(0,0,0,0.08)',
        'macos-glass-3': '0 8px 32px rgba(0,0,0,0.12)',
        'macos-inset': 'inset 0 2px 4px rgba(0,0,0,0.06)',
      },
      transitionTimingFunction: {
        'bounce': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'ease-out': 'cubic-bezier(0.0, 0.0, 0.2, 1)',
        'ease-in-out': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
        'spring': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'custom-a': 'cubic-bezier(0.25, 0.1, 0.25, 1)',
        'custom-b': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'material-standard': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
        'material-decelerate': 'cubic-bezier(0.0, 0.0, 0.2, 1)',
        'material-accelerate': 'cubic-bezier(0.4, 0.0, 1, 1)',
        'material-sharp': 'cubic-bezier(0.4, 0.0, 0.6, 1)',
        'material-emphasized': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'material-emphasized-decelerate': 'cubic-bezier(0.05, 0.7, 0.1, 1.0)',
        'material-emphasized-accelerate': 'cubic-bezier(0.3, 0.0, 0.8, 0.15)',
      },
      transitionDuration: {
        '250': '250ms',
        '350': '350ms',
        '450': '450ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '400': '400ms',
        '500': '500ms',
        '600': '600ms',
      },
      fontSize: {
        'title-1': ['2.125rem', { lineHeight: '2.5625rem', letterSpacing: '-0.5px', fontWeight: '600' }],
        'title-2': ['1.75rem', { lineHeight: '2.1rem', letterSpacing: '-0.5px', fontWeight: '600' }],
        'title-3': ['1.375rem', { lineHeight: '1.71875rem', letterSpacing: '-0.5px', fontWeight: '600' }],
        'large-title': ['2.125rem', { lineHeight: '2.7625rem', letterSpacing: '0.5px', fontWeight: '700' }],
        'headline': ['1.0625rem', { lineHeight: '1.4875rem', letterSpacing: '-0.5px', fontWeight: '600' }],
        'body': ['1.0625rem', { lineHeight: '1.4875rem', letterSpacing: '-0.5px', fontWeight: '400' }],
        'callout': ['1rem', { lineHeight: '1.45rem', letterSpacing: '-0.5px', fontWeight: '400' }],
        'subhead': ['0.9375rem', { lineHeight: '1.40625rem', letterSpacing: '-0.5px', fontWeight: '400' }],
        'footnote': ['0.8125rem', { lineHeight: '1.259375rem', letterSpacing: '-0.5px', fontWeight: '400' }],
        'caption-1': ['0.75rem', { lineHeight: '1.2rem', letterSpacing: '0', fontWeight: '400' }],
        'caption-2': ['0.6875rem', { lineHeight: '1.13125rem', letterSpacing: '0', fontWeight: '400' }],
      },
      spacing: {
        '65': '16.25rem',
        '70': '17.5rem',
        '22': '5.5rem',
      },
      width: {
        '65': '16.25rem',
        '70': '17.5rem',
      },
      height: {
        '60': '15rem',
        '70': '17.5rem',
        '80': '20rem',
        '90': '22.5rem',
        '100': '25rem',
      },
    },
  },
  plugins: [],
}