/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'tab': '834px',  // iPad竖屏
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-manrope)', 'var(--font-inter)', 'ui-sans-serif', 'system-ui'],
        display: ['var(--font-syne)', 'var(--font-inter)', 'ui-sans-serif', 'system-ui'],
        'sf-pro-display': ['"SF Pro Display"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        'sf-pro-text': ['"SF Pro Text"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
      },
      colors: {
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          400: 'var(--primary-400)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
          800: 'var(--primary-800)',
          900: 'var(--primary-900)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
          50: 'var(--secondary-50)',
          100: 'var(--secondary-100)',
          200: 'var(--secondary-200)',
          300: 'var(--secondary-300)',
          400: 'var(--secondary-400)',
          500: 'var(--secondary-500)',
          600: 'var(--secondary-600)',
          700: 'var(--secondary-700)',
          800: 'var(--secondary-800)',
          900: 'var(--secondary-900)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
          50: 'var(--accent-50)',
          100: 'var(--accent-100)',
          200: 'var(--accent-200)',
          300: 'var(--accent-300)',
          400: 'var(--accent-400)',
          500: 'var(--accent-500)',
          600: 'var(--accent-600)',
          700: 'var(--accent-700)',
          800: 'var(--accent-800)',
          900: 'var(--accent-900)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        glass: {
          DEFAULT: 'var(--glass-default)',
          light: 'var(--glass-default)',
          border: 'var(--glass-border)',
          glow: 'var(--glass-glow)',
        },
        tech: {
          darkblue: 'var(--tech-darkblue)',
          deepblue: 'var(--tech-deepblue)',
          cyan: 'var(--tech-cyan)',
          lightcyan: 'var(--tech-lightcyan)',
          sky: 'var(--tech-sky)',
          purple: 'var(--tech-purple)',
          pink: 'var(--tech-pink)',
          // 扩展色阶
          50: 'var(--tech-50)',
          100: 'var(--tech-100)',
          200: 'var(--tech-200)',
          300: 'var(--tech-300)',
          400: 'var(--tech-400)',
          500: 'var(--tech-500)',
          600: 'var(--tech-600)',
          700: 'var(--tech-700)',
          800: 'var(--tech-800)',
          900: 'var(--tech-900)',
        },
        music: {
          primary: '#fa2d2f',
          secondary: '#ff3b30',
          hover: '#ff6961',
          active: '#d32f2f',
        },
        'macos-light': {
          background: '#F5F5F7',
          surface: '#FFFFFF',
          border: 'rgba(0,0,0,0.08)',
          'text-primary': '#1D1D1F',
          'text-secondary': 'rgba(0,0,0,0.6)',
          'text-tertiary': 'rgba(0,0,0,0.4)',
          'text-disabled': 'rgba(0,0,0,0.3)',
        },
        'macos-dark': {
          background: '#000000',
          surface: '#1C1C1E',
          border: 'rgba(255,255,255,0.08)',
          'text-primary': '#FFFFFF',
          'text-secondary': 'rgba(255,255,255,0.6)',
          'text-tertiary': 'rgba(255,255,255,0.4)',
          'text-disabled': 'rgba(255,255,255,0.3)',
        },
        success: {
          DEFAULT: 'var(--success)',
          foreground: 'var(--success-foreground)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          foreground: 'var(--warning-foreground)',
        },
        error: {
          DEFAULT: 'var(--error)',
          foreground: 'var(--error-foreground)',
        },
        info: {
          DEFAULT: 'var(--info)',
          foreground: 'var(--info-foreground)',
        },
        'text-primary': 'var(--text-primary-high-contrast)',
        'text-secondary': 'var(--text-secondary-high-contrast)',
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'macos-xs': '8px',
        'macos-sm': '12px',
        'macos-md': '16px',
        'macos-lg': '20px',
        'macos-xl': '24px',
        'macos-2xl': '32px',
        'macos-3xl': '40px',
      },
      // 统一定义keyframes（只保留项目实际使用的动画）
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        'glass-float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 15px rgba(6, 182, 212, 0.3)' },
          '50%': { boxShadow: '0 0 25px rgba(6, 182, 212, 0.6)' },
        },
        'gradient-move': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-left': {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'scale-fade-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-scale-up': {
          from: { opacity: 0, transform: 'translateY(30px) scale(0.95)' },
          to: { opacity: 1, transform: 'translateY(0) scale(1)' },
        },
        'float-improved': {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px) scale(1)' },
          '25%': { transform: 'translateY(-15px) translateX(5px) scale(1.02)' },
          '50%': { transform: 'translateY(-20px) translateX(-5px) scale(1.05)' },
          '75%': { transform: 'translateY(-10px) translateX(3px) scale(1.02)' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(6, 182, 212, 0.3), 0 0 40px rgba(6, 182, 212, 0.1)' },
          '50%': { boxShadow: '0 0 30px rgba(6, 182, 212, 0.5), 0 0 60px rgba(6, 182, 212, 0.2)' },
        },
        'slide-in-right': {
          from: { opacity: 0, transform: 'translateX(30px)' },
          to: { opacity: 1, transform: 'translateX(0)' },
        },
        'vertical-scroll': {
          '0%': { transform: 'translateY(-25%)' },
          '100%': { transform: 'translateY(25%)' },
        },
        'scanline': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        'rainbow-shift': {
          '0%': { filter: 'hue-rotate(0deg)' },
          '100%': { filter: 'hue-rotate(360deg)' },
        },
      },
      // 统一定义animation（与keyframes一一对应，避免重复键）
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'glass-float': 'glass-float 6s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'gradient-move': 'gradient-move 8s ease infinite',
        'fade-in-up': 'fade-in-up 0.6s ease-out forwards',
        'slide-in-left': 'slide-in-left 0.6s ease-out forwards',
        'scale-fade-in': 'scale-fade-in 0.5s ease-out forwards',
        'fade-in': 'fade-in 0.6s ease-out forwards',
        'fade-scale-up': 'fade-scale-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'float-improved': 'float-improved 8s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        'slide-in-right': 'slide-in-right 0.6s ease-out forwards',
        'vertical-scroll': 'vertical-scroll 20s linear infinite',
        'scanline': 'scanline 2s linear infinite',
        'rainbow-shift': 'rainbow-shift 3s linear infinite',
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
      },
      transitionDelay: {
        '50': '50ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '250': '250ms',
        '300': '300ms',
        '400': '400ms',
        '500': '500ms',
      },
      boxShadow: {
        'macos-1': '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
        'macos-2': '0 3px 6px rgba(0,0,0,0.15), 0 2px 4px rgba(0,0,0,0.12)',
        'macos-3': '0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23)',
        'macos-4': '0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22)',
        'macos-5': '0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22)',
        'macos-glass-1': '0 8px 32px rgba(0,0,0,0.04)',
        'macos-glass-2': '0 8px 32px rgba(0,0,0,0.08)',
        'macos-glass-3': '0 8px 32px rgba(0,0,0,0.12)',
        'macos-inset': 'inset 0 2px 4px rgba(0,0,0,0.06)',
        'tech-cyan': '0 0 15px var(--shadow-tech-cyan)',
        'tech-purple': '0 0 15px var(--shadow-tech-purple)',
        'tech-pink': '0 0 15px var(--shadow-tech-pink)',
        'glass': 'var(--glass-shadow)',
      },
      transitionTimingFunction: {
        'bounce': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'ease-out': 'cubic-bezier(0.0, 0.0, 0.2, 1)',
        'ease-in-out': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
        'spring': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'custom-a': 'cubic-bezier(0.25, 0.1, 0.25, 1)',
        'custom-b': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'material-standard': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
        'material-decelerate': 'cubic-bezier(0.0, 0.0, 0.2, 1)',
        'material-accelerate': 'cubic-bezier(0.4, 0.0, 1, 1)',
        'material-sharp': 'cubic-bezier(0.4, 0.0, 0.6, 1)',
        'material-emphasized': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'material-emphasized-decelerate': 'cubic-bezier(0.05, 0.7, 0.1, 1.0)',
        'material-emphasized-accelerate': 'cubic-bezier(0.3, 0.0, 0.8, 0.15)',
      },
      transitionDuration: {
        '250': '250ms',
        '350': '350ms',
        '450': '450ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '400': '400ms',
        '500': '500ms',
        '600': '600ms',
      },
      fontSize: {
        'title-1': ['2.125rem', { lineHeight: '2.5625rem', letterSpacing: '-0.5px', fontWeight: '600' }],
        'title-2': ['1.75rem', { lineHeight: '2.1rem', letterSpacing: '-0.5px', fontWeight: '600' }],
        'title-3': ['1.375rem', { lineHeight: '1.71875rem', letterSpacing: '-0.5px', fontWeight: '600' }],
        'large-title': ['2.125rem', { lineHeight: '2.7625rem', letterSpacing: '0.5px', fontWeight: '700' }],
        'headline': ['1.0625rem', { lineHeight: '1.4875rem', letterSpacing: '-0.5px', fontWeight: '600' }],
        'body': ['1.0625rem', { lineHeight: '1.4875rem', letterSpacing: '-0.5px', fontWeight: '400' }],
        'callout': ['1rem', { lineHeight: '1.45rem', letterSpacing: '-0.5px', fontWeight: '400' }],
        'subhead': ['0.9375rem', { lineHeight: '1.40625rem', letterSpacing: '-0.5px', fontWeight: '400' }],
        'footnote': ['0.8125rem', { lineHeight: '1.259375rem', letterSpacing: '-0.5px', fontWeight: '400' }],
        'caption-1': ['0.75rem', { lineHeight: '1.2rem', letterSpacing: '0', fontWeight: '400' }],
        'caption-2': ['0.6875rem', { lineHeight: '1.13125rem', letterSpacing: '0', fontWeight: '400' }],
      },
      spacing: {
        '65': '16.25rem',
        '70': '17.5rem',
        '22': '5.5rem',
      },
      width: {
        '65': '16.25rem',
        '70': '17.5rem',
      },
      height: {
        '60': '15rem',
        '70': '17.5rem',
        '80': '20rem',
        '90': '22.5rem',
        '100': '25rem',
      },
    },
  },
  plugins: [],
}